colih/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('doctors.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

doctors/urls.py
import django.contrib.auth.views
from django.urls import path

from . import views 

app_name = 'doctors'
urlpatterns = [
    path('', views.index, name='index'),
    path('config/email/', views.configure_email, name='configure_email'),
    path('config/email/testar/', views.testar_smtp, name='testar_smtp'),
    path('doctors/add/', views.add_doctor, name='add_doctor'),
    path('doctors/list/', views.list_doctors, name='list_doctors'),
    path('doctors/<int:doctor_id>/edit/', views.edit_doctor, name='edit_doctor'),
    path('doctors/<int:doctor_id>/phone/<int:phone_id>/delete/', views.delete_phone, name='delete_phone'),
    path('doctors/export/xlsx/', views.export_doctors_xlsx, name='export_doctors_xlsx'),
    path('specialties/add/', views.add_specialty, name='add_specialties'),
    path('specialties/list/', views.list_specialties, name='list_specialties'),
    path('specialties/<int:specialty_id>/edit/', views.edit_specialty, name='edit_specialty'),
    path('phones/list/', views.list_phones, name='list_phones'),
    path('visits/add/', views.add_visit, name='add_visit'),
    path('visits/list/', views.list_visits, name='list_visits'),
    path('visits/<int:visit_id>/edit/', views.edit_visit, name='edit_visit'),
    path('visits/<int:visit_id>/delete/', views.delete_visit, name='delete_visit'),
    path('emergencia/add/', views.add_planilha_emergencia, name='add_planilha_emergencia'),
    path('emergencia/list/', views.list_planilhas, name='list_planilha_emergencia'),
    path('emergencia/<int:planilha_id>/edit/', views.edit_planilha_emergencia, name='edit_planilha_emergencia'),
    path('emergencia/<int:planilha_id>/submeter-gvp/', views.submeter_para_gvp, name='submeter_para_gvp'),
    path('emergencia/<int:planilha_id>/boletim/', views.gerar_boletim_whatsapp, name='gerar_boletim'),
    path('gvp/acompanhamentos/', views.list_gvp_active_cases, name='list_gvp_plan'),
    path('gvp/register/', views.add_gvp_visit, name='add_gvp_visit'),
    path('gvp/<int:planilha_id>/register/', views.add_gvp_visit, name='add_gvp_visit_direct'),
    #path('<int:doctor_id>/results/', views.results, name='results'),
    #path('<int:doctor_id>/vote/', views.vote, name='vote'),
]

doctors/models.py
from datetime import timedelta

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

PATIENT_TYPE_CHOICES = (
    ('Pediátrico', 'Pediátrico'),
    ('Adulto', 'Adulto'),
    ('Ambos', 'Ambos'),
)
STATUS_GVP_CHOICES = [
    ('PEN', 'Pendente'),
    ('AND', 'Em Acompanhamento'),
    ('FIN', 'Finalizado'),
]


class EmailConfiguration(models.Model):
    # Identificador simples para a configuração
    nome_config = models.CharField(max_length=50, default="Padrao", verbose_name="Nome da Configuração")
    
    # SMTP (Envio)
    smtp_server = models.CharField(max_length=255, verbose_name="Servidor SMTP (Ex: smtp.gmail.com)")
    smtp_port = models.IntegerField(default=587, verbose_name="Porta SMTP")
    use_tls = models.BooleanField(default=True, verbose_name="Usar TLS?")
    
    # Credenciais
    email_user = models.EmailField(verbose_name="E-mail de Origem (Usuário)")
    email_password = models.CharField(max_length=255, verbose_name="Senha do E-mail")
    
    # IMAP (Recebimento - Opcional para futuras funções)
    imap_server = models.CharField(max_length=255, blank=True, null=True, verbose_name="Servidor IMAP")

    class Meta:
        verbose_name = "Configuração de E-mail"
        verbose_name_plural = "Configurações de E-mail"

    def __str__(self):
        return f"Servidor: {self.smtp_server} ({self.email_user})"

class MembroColih(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Usuário", related_name='perfil_colih')
    ativo = models.BooleanField(default=True, verbose_name="Ativo")

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

    @property
    def total_visitas_recentes(self):
        """
        Calcula o total de visitas a MÉDICOS/HOSPITAIS (Model Visit) 
        que este usuário realizou nos últimos 30 dias.
        """
        trinta_dias_atras = timezone.now() - timedelta(days=30)
        from .models import Visit
        # Filtramos as visitas (Visit) onde este usuário é o autor/visitante
        # Ajuste o campo 'user' se o nome no seu model Visit for diferente (ex: 'membro')
        return Visit.objects.filter(
            members=self.user, 
            visit_date__gte=trinta_dias_atras
        ).count()
    
    class Meta:
        verbose_name = "Membro da COLIH"
        verbose_name_plural = "Membros da COLIH"

class MembroGvp(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Usuário")
    ativo = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

    @property
    def total_visitas_recentes(self):
        """
        Calcula o total de visitas que este usuário realizou nos últimos 30 dias.
        Útil para o Admin e para a lógica de escala.
        """
        trinta_dias_atras = timezone.now() - timedelta(days=30)
        from .models import GvpVisit
        # Filtramos as visitas onde este usuário específico está na lista de membros designados
        return GvpVisit.objects.filter(
            designated_members=self.user, 
            submission_date__gte=trinta_dias_atras
        ).count()
    
    class Meta:
        verbose_name = "Membro do GVP"
        verbose_name_plural = "Membros do GVP"

# 1. Modelo para Cidades (Padronização)
class City(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name="Cidade")
    uf = models.CharField(max_length=2, verbose_name="UF")

    class Meta:
        verbose_name = "Cidade"
        verbose_name_plural = "Cidades"
        ordering = ['name']

    def __str__(self):
        return self.name

# 2. Modelo para Hospitais (Padronização)
class Hospital(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name="Hospital")
    city = models.ForeignKey(City, on_delete=models.PROTECT, verbose_name="Cidade")
    address = models.CharField(max_length=200, verbose_name="Endereço", null=True, blank=True)
    phone = models.CharField(max_length=20, verbose_name="Telefone", null=True, blank=True)
    register_date = models.DateTimeField('Data do cadastro', auto_now_add=True)
    observation = models.TextField('Observação', null=True, blank=True)

    class Meta:
        verbose_name = "Hospital"
        verbose_name_plural = "Hospitais"
        ordering = ['name']

    def __str__(self):
        return self.name

class Specialty(models.Model):
    name = models.CharField('Nome', max_length=100)
    register_date = models.DateTimeField('Data do cadastro', auto_now_add=True)

    def __str__(self) -> str:
        return self.name

class Doctor(models.Model):
    name = models.CharField('Nome', max_length=100)
    # Alterado de CharField para ForeignKey
    city = models.ForeignKey(
        City, 
        on_delete=models.PROTECT, 
        verbose_name="Cidade",
        blank=True, 
        null=True
    )
    # Alterado de CharField para ForeignKey
    hospital = models.ForeignKey(
        Hospital, 
        on_delete=models.PROTECT, 
        verbose_name="Hospital",
        blank=True, 
        null=True
    )
    address = models.CharField('Endereço', max_length=100)
    email = models.EmailField('E-mail', null=True, blank=True)
    specialty = models.ForeignKey(Specialty, verbose_name='Especialidade 1', on_delete=models.PROTECT, related_name='doctors_primary')
    specialty2 = models.ForeignKey(Specialty, verbose_name='Especialidade 2', on_delete=models.PROTECT, related_name='doctors_secondary', blank=True, null=True)
    specialty3 = models.ForeignKey(Specialty, verbose_name='Especialidade 3', on_delete=models.PROTECT, related_name='doctors_tertiary', blank=True, null=True)
    subspecialty = models.CharField('Subespecialidade', max_length=30, null=True, blank=True)
    crm = models.CharField('CRM', max_length=80, null=True, blank=True)
    type_patient = models.CharField(
        'Tipo de paciente', 
        max_length=40, 
        choices=PATIENT_TYPE_CHOICES,
        default='Adulto' # É bom ter um padrão para facilitar
    )
    status = models.CharField('Situação', max_length=40)
    # --- NOVOS CAMPOS ADICIONADOS AQUI ---
    attends_sus = models.BooleanField('Atende SUS?', default=False)
    attends_private = models.BooleanField('Atende particular?', default=False) # <--- NOVO CAMPO
    performs_surgeries = models.BooleanField('Faz cirurgias?', default=False)
    # null=True, blank=True pois pode ser um médico novo que ainda não foi visitado
    last_visit = models.DateField('Data da última visita', null=True, blank=True) 
    is_jehovah_witness = models.BooleanField('É Testemunha de Jeová?', default=False)
    is_hid_consultant = models.BooleanField('É Consultor informado ao HID?', default=False)
    # -------------------------------------    
    obs = models.TextField('Observação', null=True, blank=True)
    user = models.ForeignKey(
        User, 
        verbose_name='Usuário (COLIH)', 
        on_delete=models.PROTECT, # Impede apagar o usuário se ele tiver médicos
        null=True,  # Permite que o campo fique vazio (caso ninguém visite ainda)
        blank=True
    )    
    register_date = models.DateTimeField('Data do cadastro', auto_now_add=True)

    def __str__(self) -> str:
        return self.name

class Phone(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, verbose_name='Médico')
    number = models.CharField('Número de telefone', max_length=20, null=True, blank=True)
    observation = models.TextField('Observação', null=True, blank=True)

class Visit(models.Model):
    # Opções de Tipo de Visita
    VISIT_TYPE_CHOICES = (
        ('Preventiva', 'Preventiva'),
        ('Apresentacao', 'Apresentação de Artigo'), # Nome sugerido
        ('Intervencao', 'Intervenção'),
    )

    # 1. Quem foi visitado?
    doctor = models.ForeignKey(
        Doctor, 
        on_delete=models.CASCADE, 
        verbose_name='Médico'
    )

    # 2. Qual o tipo da visita?
    visit_type = models.CharField(
        'Tipo de Visita', 
        max_length=20, 
        choices=VISIT_TYPE_CHOICES,
        default='Preventiva'
    )

    # 3. Local da visita (Vinculado aos hospitais cadastrados)
    # Se a visita for fora de um hospital cadastrado, pode deixar em branco.
    hospital = models.ForeignKey(
        Hospital, 
        on_delete=models.SET_NULL, # Se apagar o hospital, mantém o histórico da visita
        verbose_name='Local da Visita (Hospital)',
        null=True, 
        blank=True
    )
    
    # 4. Qual artigo/assunto?
    article = models.CharField('Artigo Apresentado / Assunto', max_length=200, null=True, blank=True)

    # 5. Especialidade focada na visita
    specialty = models.ForeignKey(
        Specialty, 
        on_delete=models.PROTECT, 
        verbose_name='Especialidade Abordada'
    )

    # 6. Datas
    visit_date = models.DateField('Data da Visita') # Data manual (quando ocorreu)
    created_at = models.DateTimeField('Data do Lançamento', auto_now_add=True) # Automático (sistema)

    # 7. Quem realizou a visita? (ManyToManyField é o ideal aqui)
    members = models.ManyToManyField(
        User, 
        verbose_name='Membros Visitantes',
        related_name='visits' 
    )

    # Campo extra para anotações do resultado da visita
    outcome = models.TextField('Desfecho / Resultado', null=True, blank=True)

    class Meta:
        verbose_name = "Visita"
        verbose_name_plural = "Visitas"
        ordering = ['-visit_date'] # Ordena da mais recente para a mais antiga

    def __str__(self):
        return f"{self.get_visit_type_display()} - {self.doctor.name} ({self.visit_date})"

class PlanilhaEmergencia(models.Model):
    # --- Choices ---
    SEXO_CHOICES = [
        ('M', 'Masculino'),
        ('F', 'Feminino'),
    ]
    
    TIPO_ATENDIMENTO_CHOICES = [
        ('PAR', 'Particular'),
        ('PUB', 'Público'),
    ]

    # --- 1. Notificação ---

doctors/templates/visits/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block corpo %}
<div class="container-fluid">
  <div>
    <form action="." class="form-horizontal" method="post">
      <div class="row">
        {% csrf_token %}
        <div class="col-lg-6">
          {% crispy form %}
        </div>
        <div class="col-lg-6">
          <img class="img-fluid center" style="width: inherit; border-style: double;" src="/static/img/doctor.jpg">
        </div>
      </div>
    </form>
  </div>
</div>
<br>
{% endblock %}

doctors/templates/visits/delete.html
{% extends 'base.html' %}

{% block corpo %}
<div class="row justify-content-center">
    <div class="col-lg-6">
        <div class="card shadow mb-4 border-left-danger">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-danger">Confirmação de Exclusão</h6>
            </div>
            <div class="card-body">
                <p>Tem a certeza que deseja excluir o registo desta visita?</p>
                
                <div class="alert alert-secondary">
                    <strong>Médico:</strong> {{ visit.doctor.name }}<br>
                    <strong>Data:</strong> {{ visit.visit_date|date:"d/m/Y" }}<br>
                    <strong>Tipo:</strong> {{ visit.get_visit_type_display }}
                </div>

                <p class="text-danger small">Esta ação não pode ser desfeita.</p>

                <form method="post">
                    {% csrf_token %}
                    <a href="/visits/list/" class="btn btn-secondary">Cancelar</a>
                    
                    <button type="submit" class="btn btn-danger">Sim, Excluir</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

doctors/templates/visits/list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block corpo %}

{% if perms.doctors.add_visit %}
<div class="col-lg-12">
  <a href="/visits/add/" ><button class="btn btn-info"><span class="fas fa-plus"></span> Registrar Nova Visita</button></a>
</div>
<br>
{% endif %}

<div class="card shadow mb-4">
  <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse"
      role="button" aria-expanded="true" aria-controls="collapseCardExample">
      <h6 class="m-0 font-weight-bold text-primary">Filtro de Pesquisa</h6>
  </a>
  <div class="collapse hide" id="collapseCardExample">
      <div class="card-body">
        <form action="." method="get">
          <div class="row">
            <div class="col-lg-4">
              {{ form.doctor_name|as_crispy_field }}
            </div>
            <div class="col-lg-4">
              {{ form.visit_type|as_crispy_field }}
            </div>
            <div class="col-lg-4">
              {{ form.specialty|as_crispy_field }}
            </div>
          </div>
          <div class="col-lg-12">
            <button class="btn btn-primary" type="submit">Buscar</button>
            <a href="." class="btn btn-secondary">Limpar</a>
          </div>
        </form>
      </div>
  </div>
</div>

<div class="card shadow mb-4">
  <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Visitas Registradas</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered table-striped" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th scope="col">Data</th>
            <th scope="col">Médico</th>
            <th scope="col">Tipo</th>
            <th scope="col">Especialidade</th>
            <th scope="col">Local</th>
            {% if perms.doctors.change_visit %}<th scope="col">Ações</th>{% endif %}
          </tr>
        </thead>
        <tbody>
          {% for visit in visits %}
          <tr>
            <td>{{ visit.visit_date|date:"d/m/Y" }}</td>
            
            <td>{{ visit.doctor.name }}</td>
            
            <td>{{ visit.get_visit_type_display }}</td>
            
            <td>{{ visit.specialty.name }}</td>
            
            <td>
                {% if visit.hospital %}
                    {{ visit.hospital.name }}
                {% else %}
                    -
                {% endif %}
            </td>

            {% if perms.doctors.change_visit %}
            <td>
              <a href="/visits/{{ visit.id }}/edit/" >
                <button class="btn btn-secondary btn-sm" title="Edição"><span class="fas fa-edit"></span></button>
              </a>
              <a href="/visits/{{ visit.id }}/delete/" >
                <button class="btn btn-danger btn-sm" title="Edição"><span class="fas fa-trash"></span></button>
              </a>
            </td>
            {% endif %}
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script src="/static/sb/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="/static/sb/vendor/datatables/dataTables.bootstrap4.min.js"></script>

<script src="/static/sb/js/demo/datatables-demo.js"></script>
{% endblock %}